# Colors oh-lucy
window:
  decorations: None

# The definition of color schemes.
schemes:
  oh-lucy: &oh-lucy
    primary:
      background: '#1E1D23'
      foreground: '#DED7D0'
    normal:
      black:   '#938884'
      red:     '#FF7DA3'
      green:   '#7EC49D'
      yellow:  '#EFD472'
      blue:    '#8BB8D0'
      magenta: '#BDA9D4'
      cyan:    '#BDA9D4'
      white:   '#DED7D0'
    bright:
      black:   '#938884'
      red:     '#FF7DA3'
      green:   '#7EC49D'
      yellow:  '#EFD472'
      blue:    '#8BB8D0'
      magenta: '#BDA9D4'
      cyan:    '#BDA9D4'
      white:   '#DED7D0'

  oxocarbon: &oxocarbon
    primary:
      background: "#161616"
      foreground: "#ffffff"
    search:
      matches:
        foreground: CellBackground
        background: '#ee5396'
      footer_bar:
        background: '#262626'
        foreground: '#ffffff'
    normal:
      black: "#262626"
      magenta: "#ff7eb6"
      green: "#42be65"
      yellow: "#ffe97b"
      blue: "#33b1ff"
      red: "#ee5396"
      cyan: "#3ddbd9"
      white: "#dde1e6"
    bright:
      black: "#393939"
      magenta: "#ff7eb6"
      green: "#42be65"
      yellow: "#ffe97b"
      blue: "#33b1ff"
      red: "#ee5396"
      cyan: "#3ddbd9"
      white: "#ffffff"

# Apply the color scheme.
colors: *oxocarbon

font:
  # The font family
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Regular
  size: 12
  bold:
    family: JetBrainsMono Nerd Font Mono
    style: Regular

  offset:
    x: 0
    y: 8
