#! /bin/sh

$HOME.screenlayout/bspwm_display.sh
pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output eDP-1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output HDMI-1 --mode 1920x1080 --pos 0x0 --rotate normal

xsetroot -cursor_name left_ptr &
xsetroot -solid "#ffffff"
picom --config ~/.config/picom/picom.conf &
# picom -f &
$HOME/.config/polybar/launch.sh
feh --bg-scale ~/Downloads/walls/night.jpg

bspc monitor HDMI-1 -d I II III IV V
bspc monitor eDP-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config focused_border_color \#8FBCBB
bspc config normal_border_color \#4C566A
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
